### PR TITLE
getAndParseGSEmatrix minor fix

### PR DESCRIPTION
**Pull request by martinguerrero89**
a minor fix that solves the URL issue of getDirListing, from getAndParseGSEMatrices

### CODE REVIEW

**Comment by seandavi** [comment]
Thanks for the pull request. However, I the problem that this addresses has already been fixed and this pull request introduces an error that did not exist, so I am going to close this for now, but we can continue to discuss here if needed. 

Again, thanks for taking the time to work on this!

**Comment by aushev** [comment]
Sean @seandavi could you please specify - in which version it has already been fixed? I keep having the same problem (error in `getAndParseGSEMatrices()` because first item of `getDirListing()` is a link to a parent dir). Here is my sessionInfo:
`
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.28.0 limma_3.32.10        GEOquery_2.42.0      Biobase_2.36.2       BiocGenerics_0.22.0 

loaded via a namespace (and not attached):
[1] httr_1.3.1      compiler_3.4.3  R6_2.2.2        tools_3.4.3     RCurl_1.95-4.10 bitops_1.0-6    XML_3.98-1.10  `

**Comment by seandavi** [comment]
@aushev, could you upgrade to the current version of GEOquery (2.46.15) and let me know if you still see the problem?

**Comment by seandavi** [comment]
Glad to hear it. Thanks for keeping me honest.

**Pull request closed without merging**
